import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url),project='../';
const R=require(project+'public/rules.js');require(project+'/public/referee.js');
const Ref=globalThis.GameReferee,AI=require(project+'/public/ai-worker.js');
const sides=['player','enemy'];
const cells=Array.from({length:64},(_,i)=>R.coord(i%8,Math.floor(i/8)));
const checkpointContext=vm.createContext({window:{}});
vm.runInContext(fs.readFileSync(new URL('../public/local-checkpoint.js',import.meta.url),'utf8'),checkpointContext);
const checkpoint=checkpointContext.window.BNSLocalCheckpoint.create('classic',{coords:cells,names:R.defs.map(d=>d.name)});
const act=(c,a)=>{switch(a?.type){case'select':return c.selectPiece(a.pieceId);case'startMove':return c.startMove();case'moveStep':return c.moveStep(a.to);case'stopMove':return c.stopMove();case'startAttack':return c.startAttack();case'attack':return c.attack(a.to);case'pyroSelect':return c.selectPyroTarget(a.to);case'pyroConfirm':return c.confirmPyroAttack();case'sureShotConfirm':return c.confirmSureShot();case'paranoiaSelect':return c.selectParanoiaTarget(a.to);case'paranoiaConfirm':return c.confirmParanoia();case'kamikazeConfirm':return c.confirmKamikaze();case'startAbility':return c.startAbility();case'seer':return c.useSeer(a.cells);case'raise':return c.raiseAt(a.to);case'mirror':return c.placeMirror(a.to);case'awaken':return c.awakenTree(a.to);case'trap':return c.placeTrap(a.to);case'bard':return c.bardBuff(a.targetPieceId,a.stat);case'absorbRock':return c.absorbRock(a.coord);case'shieldLink':return c.shieldLink(a.targetPieceId||null);case'sabotage':return c.sabotageBase(a.baseId,a.bonusId,a.targetPieceId||null);case'combatChoice':return c.chooseCombatPosition(!!a.advance);case'doppelChoice':return c.chooseDoppelCopy(!!a.copyNew);case'end':return c.endActivation();default:return{ok:false,status:'unknown '+a?.type};}};
function invariantErrors(ref){const s=JSON.parse(ref.exportState()),alive=sides.flatMap(side=>(s.pieces[side]||[]).filter(p=>p.alive)),errs=[];for(const p of alive){if(!cells.includes(p.coord))errs.push(`invalid coord ${p.id}:${p.coord}`);const linked=p.linkedToId&&alive.find(q=>q.id===p.linkedToId&&q.owner===p.owner);if(p.linkedToId&&(!linked||linked.coord!==p.coord))errs.push(`broken link ${p.id}->${p.linkedToId}`);}for(const c of cells){const here=alive.filter(p=>p.coord===c),owners=new Set(here.map(p=>p.owner));if(owners.size>1)errs.push(`opponents share ${c}: ${here.map(p=>p.owner+':'+p.name).join(',')}`);for(const side of sides){const own=here.filter(p=>p.owner===side),shield=p=>p.name==='Escudeiro'||(p.name==='Doppelgänger'&&p.copied==='Escudeiro');if(own.length>2)errs.push(`three allies share ${c}`);if(own.length===2&&!own.some(shield))errs.push(`invalid ally stack ${c}`);}}return[...new Set(errs)];}
const valid=['A2','C2','E2','H2'],bases=['B1','G1'],defs=R.defs.map(x=>x.name),diffs=['easy','normal','hard','extreme'];
const out={games:0,completed:0,actions:0,invalid:[],stalled:[],invariants:[],results:{}};
const originalRandom=Math.random,seeded=seed=>()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};
for(const [di,difficulty] of diffs.entries())for(let game=0;game<Number(process.env.GAMES||20);game++){
  const seed=260000+(Number(process.env.SEED_OFFSET)||0)+di*1000+game;Math.random=seeded(seed);
  const team=Array.from({length:4},(_,i)=>defs[(di*20+game*4+i)%defs.length]);const ref=new Ref(),start=ref.startGame(team.map((name,i)=>({name,coord:valid[i]})),bases,difficulty);if(!start.ok)throw Error(start.status);AI.setDifficulty(difficulty);AI.resetMemory(ref.createClient('enemy').getView());let last=null,steps=0;
  for(;steps<5000;steps++){const raw=JSON.parse(ref.exportState());if(raw.gameOver)break;let side=raw.pendingCombat?.winnerSide||sides.find(x=>raw.doppelChoice?.[x])||raw.turn,c=ref.createClient(side),view=c.getView(),action;
    if(side==='enemy'){action=AI.decide(view,last);AI.rememberIssued(action,view);}else if(view.pendingCombat)action={type:'combatChoice',advance:false};else if(view.doppelChoice)action={type:'doppelChoice',copyNew:false};else if(!view.activation)action={type:'select',pieceId:view.availablePieceIds[0]};else action={type:'end'};
    const res=act(c,action);out.actions++;if(side==='enemy')last={action:{...action},ok:res?.ok!==false,status:res?.status||''};if(!res?.ok)out.invalid.push({difficulty,game,step:steps,side,action,res});const errs=invariantErrors(ref);if(process.env.CHECKPOINT==='1'&&!checkpoint.valid(ref.exportState()))errs.push('checkpoint inválido');if(errs.length){const state=JSON.parse(ref.exportState());out.invariants.push({difficulty,game,step:steps,side,action,res,errs,related:sides.flatMap(x=>state.pieces[x]).filter(p=>p.alive&&(p.linkedToId||errs.some(e=>e.includes(p.id)||e.includes(p.coord)))),history:Object.fromEntries(sides.map(x=>[x,state.history[x].slice(0,8)]))});break;}
  }
  out.games++;const end=JSON.parse(ref.exportState());if(end.gameOver){out.completed++;out.results[end.result]=(out.results[end.result]||0)+1;}else out.stalled.push({difficulty,game,seed,round:end.round,steps,turn:end.turn,playerAlive:end.pieces.player.filter(p=>p.alive).map(p=>({id:p.id,name:p.name,coord:p.coord,hp:p.hp})),enemyAlive:end.pieces.enemy.filter(p=>p.alive).map(p=>({id:p.id,name:p.name,identity:p.identity,coord:p.coord,hp:p.hp,linkedToId:p.linkedToId,copied:p.copied})),bases:end.bases,history:end.history.enemy.slice(0,12),intel:end.intel.enemy});
}
Math.random=originalRandom;
console.log(JSON.stringify(out,null,2));
if(out.invalid.length||out.invariants.length||out.stalled.length)process.exitCode=1;
